FROM registry.access.redhat.com/ubi9/nodejs-20:1-24

RUN npm install --global @antora/cli@3.1 @antora/site-generator@3.1 http-server@14.1.1

COPY ./entrypoint.sh /usr/local/bin/entrypoint.sh

WORKDIR /antora

EXPOSE 8080

ENTRYPOINT ["entrypoint.sh"]

CMD ["npx", "http-server", "www", "-c-1", "-p", "8080"]
