FROM registry.access.redhat.com/ubi9/nodejs-20:1-24

ARG CREATED_AT=none
ARG GITHUB_SHA=none

LABEL org.opencontainers.image.created="$CREATED_AT"
LABEL org.opencontainers.image.revision="$GITHUB_SHA"

LABEL org.opencontainers.image.title="Antora Viewer"
LABEL org.opencontainers.image.description="Build and serve Antora websites."
LABEL org.opencontainers.image.url="https://github.com/juliaaano/antora-viewer"
LABEL org.opencontainers.image.source="git@github.com:juliaaano/antora-viewer"
LABEL org.opencontainers.image.documentation="https://github.com/juliaaano/antora-viewer"
LABEL org.opencontainers.image.authors="juliaaano"
LABEL org.opencontainers.image.vendor="juliaaano"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.version="1.0.0"

USER root

RUN npm install --global @antora/cli@3.1 @antora/site-generator@3.1 http-server@14.1.1

COPY ./entrypoint.sh /usr/local/bin/entrypoint.sh

WORKDIR /antora

EXPOSE 8080

USER 1001

ENTRYPOINT ["entrypoint.sh"]

CMD ["npx", "http-server", "www", "-c-1", "-p", "8080"]
